CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) UNIQUE,
  lastName VARCHAR(255) UNIQUE,
  address1 VARCHAR(255) UNIQUE,
  address2 VARCHAR(255) UNIQUE,
  city VARCHAR(255) UNIQUE,
  zip VARCHAR(255) UNIQUE,
  state VARCHAR(255) UNIQUE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);