CREATE TABLE carts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  itemTotal DECIMAL(10, 2) NOT NULL,
  cartTotal DECIMAL(10, 2) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id)
);
